.nh
.TH "GH-CODESPACE-REBUILD" "1" "Oct 2022" "GitHub CLI 2.18.1" "GitHub CLI manual"

.SH NAME
.PP
gh-codespace-rebuild - Rebuild a codespace


.SH SYNOPSIS
.PP
\fB\fCgh codespace rebuild [flags]\fR


.SH OPTIONS
.TP
\fB\fC-c\fR, \fB\fC--codespace\fR \fB\fC<string>\fR
Name of the codespace


.SH SEE ALSO
.PP
\fB\fCgh-codespace(1)\fR
